export { HeroSection } from './HeroSection'
export { MarketTrend } from './MarketTrend/MarketTrend'
export { Features } from './Features/Features'
export { New } from './New/New'
export { GetStarted } from './GetStarted/GetStarted'
export { Learn } from './Learn/Learn'